// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf9ZRZOsJTteTX6WtW7MDKqCFxcj98Gf0',
    appId: '1:176446686294:web:4b3e59b1e9d02a37c227f7',
    messagingSenderId: '176446686294',
    projectId: 'talknplan-265c1',
    authDomain: 'talknplan-265c1.firebaseapp.com',
    databaseURL: 'https://talknplan-265c1-default-rtdb.firebaseio.com/',
    storageBucket: 'talknplan-265c1.appspot.com',
    measurementId: 'G-1GHL1S8322',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNVHRuvV9gdGHHTT--ZmhogOFG9tnTPMo',
    appId: '1:176446686294:android:b5ae0b290cf06503c227f7',
    messagingSenderId: '176446686294',
    projectId: 'talknplan-265c1',
    storageBucket: 'talknplan-265c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgIKQBkR0b_xgUsUvzEoF6ukalFxrhYpQ',
    appId: '1:176446686294:ios:ea151dcab01d41e7c227f7',
    messagingSenderId: '176446686294',
    projectId: 'talknplan-265c1',
    storageBucket: 'talknplan-265c1.appspot.com',
    iosBundleId: 'com.example.aiScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgIKQBkR0b_xgUsUvzEoF6ukalFxrhYpQ',
    appId: '1:176446686294:ios:ea151dcab01d41e7c227f7',
    messagingSenderId: '176446686294',
    projectId: 'talknplan-265c1',
    storageBucket: 'talknplan-265c1.appspot.com',
    iosBundleId: 'com.example.aiScheduler',
  );
}
